
IF OBJECT_ID('CUSTOMERS_401001', 'U') IS NOT NULL
    DROP TABLE CUSTOMERS_401001;
GO

CREATE TABLE CUSTOMERS_401001 (
    ProductKey INT,
    CurrencyAlternateKey VARCHAR(10),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    OrderDateKey INT,
    OrderQuantity INT,
    UnitPrice DECIMAL(10,2),
    SecretCode VARCHAR(10)
);
GO


SELECT * FROM CUSTOMERS_401001